/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./../components/App/Footer.vue')['default']
    AppHeader: typeof import('./../components/App/Header.vue')['default']
    AppNavbar: typeof import('./../components/App/Navbar.vue')['default']
    AppSidebar: typeof import('./../components/App/Sidebar.vue')['default']
    IndexArticleCard: typeof import('./../components/Index/ArticleCard.vue')['default']
    IndexArticleList: typeof import('./../components/Index/ArticleList.vue')['default']
    IndexCardBody: typeof import('./../components/Index/CardBody.vue')['default']
    IndexSidebar: typeof import('./../components/Index/Sidebar.vue')['default']
    PostBodyCard: typeof import('./../components/Post/BodyCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
